#!/usr/bin/env python
import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

try:
    branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).decode('utf-8').strip()
    # branch = check_output(['git', 'rev-parse', ' --abbrev-ref', 'HEAD']).decode('utf-8').strip()
    print('\n hook: '+branch+'\n')
    # if(branch != 'HEAD'):
    regex = r'(\w+-\d+)'
    if re.match(regex, branch):
        issue = re.match(regex, branch).group(1)
        with open(commit_msg_filepath, 'r+') as fh:
            commit_msg = fh.read()
            fh.seek(0, 0)
            fh.write('[%s] %s' % (issue, commit_msg))
except:
    print('\nprepare-commit-msg did not run\n')